### ISSUE TITLE
Consolidate auth functions

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-redux-api#56]
Instead of a separate `isAuthenticatedWithContext` function, could we just pass the context to `isAuthenticated`?

E.g. `isAuthenticated('context)` or `isAuthenticated({ context: 'context })`

**Comment by rkillackey** [comment]
This sounds reasonable to me. So without the context, it just looks for the token, otherwise looks for token + context. I think just passing in the context string would work.

**Comment by davemcorwin** [comment]
I'm mixed on it, if we do it, we have to be careful. For example, we have to check explicitly for presence of the passed argument, otherwise I can see a situation where:

* the user is authenticated with with context === 'foo'
* `isAuthenticated(someContext)` is called where `someContext === null`
* returns true if we only check for truthiness since the user is logged in, but we would have expected false...

**Comment by dpikt** [comment]
@davemcorwin Passing a `null` context is just asking for trouble :D  But I agree we need to check for presence. What do you think about param vs config object? Do you think there could be other params we might want to pass it in the future?

**Comment by davemcorwin** [comment]
i suppose the object syntax would be more flexible in case other stuff gets added. This doesn't seem to be high priority, so moving to the backlog.

**Comment by dpikt** [comment]
Another chance to use the deprecation helper! 🙌
